//! Migration engine: applies approved remediations for real, with a snapshot
//! taken before every file change so any migration can be rolled back.
//!
//! SSH migration = generate hybrid-ready Ed25519 keypair + wire it into
//! ~/.ssh/config through a clearly-marked managed block. Rollback restores the
//! exact config bytes from before the change.

use crate::scanner;
use crate::store::Store;
use std::path::PathBuf;

const BLOCK_START: &str = "# >>> CryptiQ Personal managed block — do not edit >>>";
const BLOCK_END: &str = "# <<< CryptiQ Personal managed block <<<";

fn ssh_config_path() -> Result<PathBuf, String> {
    Ok(dirs::home_dir().ok_or("no home directory")?.join(".ssh").join("config"))
}

fn managed_block() -> String {
    format!(
        "{BLOCK_START}\n\
         # Prefer the quantum-migration key generated by CryptiQ Personal.\n\
         # Your original keys remain configured and untouched.\n\
         Host *\n\
         \x20\x20IdentityFile ~/.ssh/cryptiq_ed25519\n\
         {BLOCK_END}\n"
    )
}

/// Apply the SSH migration for a finding: new Ed25519 keypair + config block.
pub fn apply_ssh_migration(store: &Store, finding_id: &str) -> Result<String, String> {
    let key_msg = scanner::generate_replacement_key()?;

    let config = ssh_config_path()?;
    let existing = std::fs::read_to_string(&config).ok();

    if existing.as_deref().unwrap_or("").contains(BLOCK_START) {
        store.log_remediation(finding_id, "ssh_migration", &key_msg);
        return Ok(format!("{key_msg}. SSH config already routes through the new key."));
    }

    // Snapshot BEFORE touching anything (None = file did not exist).
    store.save_snapshot(finding_id, &config.to_string_lossy(), existing.as_deref());

    let mut new_content = existing.unwrap_or_default();
    if !new_content.is_empty() && !new_content.ends_with('\n') {
        new_content.push('\n');
    }
    new_content.push('\n');
    new_content.push_str(&managed_block());
    std::fs::write(&config, &new_content).map_err(|e| e.to_string())?;

    let msg = format!(
        "{key_msg}. Added managed block to {} so SSH offers the new key first. \
         Upload ~/.ssh/cryptiq_ed25519.pub to GitHub/your servers to complete the swap.",
        config.display()
    );
    store.log_remediation(finding_id, "ssh_migration", &msg);
    Ok(msg)
}

/// Wi-Fi remediation: mark untrusted networks as force-tunneled. The tunnel
/// itself is the shield connection; this persists the policy.
pub fn apply_wifi_policy(store: &Store, finding_id: &str) -> Result<String, String> {
    store.set_setting("force_tunnel_untrusted", "1");
    let msg = "Untrusted-network policy enabled: CryptiQ will require the quantum-safe \
               tunnel whenever this laptop is on WPA2/open Wi-Fi."
        .to_string();
    store.log_remediation(finding_id, "wifi_policy", &msg);
    Ok(msg)
}

/// Roll back a previously applied migration by restoring the pre-change snapshot.
pub fn rollback(store: &Store, finding_id: &str) -> Result<String, String> {
    if finding_id == "net:wifi" {
        store.set_setting("force_tunnel_untrusted", "0");
        let msg = "Untrusted-network policy disabled.".to_string();
        store.log_remediation(finding_id, "rollback", &msg);
        return Ok(msg);
    }

    let snap = store
        .latest_snapshot(finding_id)
        .ok_or("no snapshot recorded for this migration")?;

    match snap.content {
        Some(bytes) => std::fs::write(&snap.file_path, bytes).map_err(|e| e.to_string())?,
        None => {
            // File didn't exist before the migration — remove what we created.
            if std::path::Path::new(&snap.file_path).exists() {
                std::fs::remove_file(&snap.file_path).map_err(|e| e.to_string())?;
            }
        }
    }

    let msg = format!(
        "Restored {} to its pre-migration state. The generated keypair at \
         ~/.ssh/cryptiq_ed25519 was kept (delete it manually if it was never uploaded anywhere).",
        snap.file_path
    );
    store.log_remediation(finding_id, "rollback", &msg);
    Ok(msg)
}
