//! Migration engine: applies approved remediations for real, with a snapshot
//! taken before every file change so any migration can be rolled back.
//!
//! SSH migration = generate hybrid-ready Ed25519 keypair + wire it into
//! ~/.ssh/config through a clearly-marked managed block. Rollback restores the
//! exact config bytes from before the change.

use crate::scanner;
use crate::store::Store;
use serde::Serialize;
use std::path::PathBuf;

const BLOCK_START: &str = "# >>> CryptiQ Personal managed block — do not edit >>>";
const BLOCK_END: &str = "# <<< CryptiQ Personal managed block <<<";
/// Canonical snapshot key for ~/.ssh/config. Multiple ssh:*.pub findings all
/// touch the same file — sharing one snapshot prevents rollback collisions.
const SSH_CONFIG_SNAPSHOT: &str = "ssh:config";

fn is_ssh_key_finding(id: &str) -> bool {
    id.starts_with("ssh:")
        && id != "ssh:known_hosts"
        && id != "ssh:none"
        && id != SSH_CONFIG_SNAPSHOT
}

fn ssh_config_path() -> Result<PathBuf, String> {
    Ok(dirs::home_dir().ok_or("no home directory")?.join(".ssh").join("config"))
}

/// True when the local OpenSSH supports the post-quantum hybrid key exchange.
fn ssh_supports_pq_kex() -> bool {
    std::process::Command::new("ssh")
        .args(["-Q", "kex"])
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).contains("sntrup761x25519-sha512"))
        .unwrap_or(false)
}

fn managed_block() -> String {
    let kex_line = if ssh_supports_pq_kex() {
        "\x20\x20# Post-quantum hybrid key exchange (NTRU Prime + X25519) first;\n\
         \x20\x20# servers without it fall back to the classical algorithms after.\n\
         \x20\x20KexAlgorithms sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org\n"
    } else {
        ""
    };
    format!(
        "{BLOCK_START}\n\
         # Prefer the quantum-migration key generated by CryptiQ Personal.\n\
         # Your original keys remain configured and untouched.\n\
         Host *\n\
         \x20\x20IdentityFile ~/.ssh/cryptiq_ed25519\n\
         {kex_line}\
         \x20\x20# Prefer Ed25519 host keys; keep ECDSA/RSA-SHA2 fallbacks so no\n\
         \x20\x20# existing server becomes unreachable. Legacy ssh-rsa (SHA-1) is out.\n\
         \x20\x20HostKeyAlgorithms ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256\n\
         {BLOCK_END}\n"
    )
}

/// Insert the managed block, or replace an existing (possibly outdated) one.
/// Returns (new_content, changed).
fn upsert_managed_block(existing: &str) -> (String, bool) {
    let block = managed_block();
    match (existing.find(BLOCK_START), existing.find(BLOCK_END)) {
        (Some(start), Some(end_marker)) if end_marker >= start => {
            let end = end_marker + BLOCK_END.len();
            // Consume the trailing newline of the old block if present.
            let end = if existing[end..].starts_with('\n') { end + 1 } else { end };
            let current = &existing[start..end];
            if current == block {
                return (existing.to_string(), false);
            }
            let mut out = String::with_capacity(existing.len() + block.len());
            out.push_str(&existing[..start]);
            out.push_str(&block);
            out.push_str(&existing[end..]);
            (out, true)
        }
        _ => {
            let mut out = existing.to_string();
            if !out.is_empty() && !out.ends_with('\n') {
                out.push('\n');
            }
            if !out.is_empty() {
                out.push('\n');
            }
            out.push_str(&block);
            (out, true)
        }
    }
}

/// Apply the SSH migration for a finding: new Ed25519 keypair + config block
/// (post-quantum SSH key exchange preference + Ed25519-first host keys).
pub fn apply_ssh_migration(store: &Store, finding_id: &str) -> Result<String, String> {
    if !is_ssh_key_finding(finding_id) {
        return Err(format!(
            "{finding_id} is not an auto-migratable SSH key finding"
        ));
    }
    let key_msg = scanner::generate_replacement_key()?;

    let config = ssh_config_path()?;
    let existing = std::fs::read_to_string(&config).ok();

    let (new_content, changed) = upsert_managed_block(existing.as_deref().unwrap_or(""));
    if !changed {
        // Config already migrated; still mark this finding applied so the UI
        // doesn't keep offering a no-op queue item.
        let msg = format!(
            "{key_msg}. SSH config already carries the current CryptiQ managed block."
        );
        store.log_remediation(finding_id, "ssh_migration", &msg);
        return Ok(msg);
    }

    // Snapshot once under the canonical id so later ssh:*.pub applies don't
    // overwrite the pre-migration baseline (and break rollback of the first).
    let config_already = store
        .applied_findings()
        .iter()
        .any(|id| id == SSH_CONFIG_SNAPSHOT);
    if !config_already {
        store.save_snapshot(
            SSH_CONFIG_SNAPSHOT,
            &config.to_string_lossy(),
            existing.as_deref(),
        );
        store.log_remediation(
            SSH_CONFIG_SNAPSHOT,
            "ssh_migration",
            "Canonical SSH config snapshot taken before CryptiQ managed block.",
        );
    }
    std::fs::write(&config, &new_content).map_err(|e| e.to_string())?;

    let msg = format!(
        "{key_msg}. Managed block written to {}: SSH now offers the new key first and \
         prefers OpenSSH's post-quantum hybrid key exchange where servers support it. \
         Upload ~/.ssh/cryptiq_ed25519.pub to GitHub/your servers to complete the swap.",
        config.display()
    );
    store.log_remediation(finding_id, "ssh_migration", &msg);
    Ok(msg)
}

/// Git signing migration: switch commit signing from GPG (typically RSA) to
/// SSH signing with the CryptiQ Ed25519 key. Snapshot of ~/.gitconfig taken
/// first, so rollback restores the previous signing setup byte-for-byte.
pub fn apply_git_signing(store: &Store, finding_id: &str) -> Result<String, String> {
    let key_msg = scanner::generate_replacement_key()?;
    let home = dirs::home_dir().ok_or("no home directory")?;
    let gitconfig = home.join(".gitconfig");
    let existing = std::fs::read_to_string(&gitconfig).ok();

    store.save_snapshot(finding_id, &gitconfig.to_string_lossy(), existing.as_deref());

    let signing_key = home.join(".ssh").join("cryptiq_ed25519.pub");
    let run = |args: &[&str]| -> Result<(), String> {
        let out = std::process::Command::new("git")
            .args(args)
            .output()
            .map_err(|e| format!("could not run git: {e}"))?;
        if out.status.success() {
            Ok(())
        } else {
            Err(String::from_utf8_lossy(&out.stderr).trim().to_string())
        }
    };
    run(&["config", "--global", "gpg.format", "ssh"])?;
    run(&[
        "config",
        "--global",
        "user.signingkey",
        &signing_key.to_string_lossy(),
    ])?;
    // Without this, Git only *can* sign — it won't actually sign commits.
    run(&["config", "--global", "commit.gpgsign", "true"])?;

    let msg = format!(
        "{key_msg}. Git now signs every commit with Ed25519 via SSH ({}). \
         Add this key as a signing key on GitHub (Settings → SSH and GPG keys → \
         New SSH key → type: Signing Key) so commits show as verified.",
        signing_key.display()
    );
    store.log_remediation(finding_id, "git_signing", &msg);
    Ok(msg)
}

/// Wi-Fi remediation: mark untrusted networks as force-tunneled. The tunnel
/// itself is the shield connection; this persists the policy.
pub fn apply_wifi_policy(store: &Store, finding_id: &str) -> Result<String, String> {
    store.set_setting("force_tunnel_untrusted", "1");
    let msg = "Untrusted-network policy enabled: CryptiQ will require the quantum-safe \
               tunnel whenever this laptop is on WPA2/open Wi-Fi."
        .to_string();
    store.log_remediation(finding_id, "wifi_policy", &msg);
    Ok(msg)
}

/// Full technical record of an applied migration, for the audit view:
/// the exact file changed, its content before and after, and the fingerprint
/// of any key material that was generated.
#[derive(Serialize)]
pub struct MigrationDetail {
    pub finding_id: String,
    pub action: String,
    pub applied_at: String,
    pub summary: String,
    /// None for policy-only migrations (no file was touched).
    pub file_path: Option<String>,
    pub before: Option<String>,
    pub after: Option<String>,
    pub new_key_path: Option<String>,
    pub new_key_fingerprint: Option<String>,
}

pub fn migration_detail(store: &Store, finding_id: &str) -> Result<MigrationDetail, String> {
    let entry = store
        .latest_remediation(finding_id)
        .ok_or("no applied migration for this finding")?;

    let snap_id = if is_ssh_key_finding(finding_id) || finding_id == SSH_CONFIG_SNAPSHOT {
        SSH_CONFIG_SNAPSHOT
    } else {
        finding_id
    };
    let snap = store.latest_snapshot(snap_id);
    let (file_path, before, after) = match snap {
        Some(s) => {
            let after = std::fs::read_to_string(&s.file_path).ok();
            let before = s.content.map(|b| String::from_utf8_lossy(&b).to_string());
            (Some(s.file_path), before, after)
        }
        None => (None, None, None),
    };

    // Fingerprint of the generated migration key, if key material was involved.
    let (new_key_path, new_key_fingerprint) = if matches!(
        entry.action.as_str(),
        "ssh_migration" | "git_signing"
    ) {
        let pubkey = dirs::home_dir()
            .map(|h| h.join(".ssh").join("cryptiq_ed25519.pub"))
            .filter(|p| p.exists());
        match pubkey {
            Some(p) => {
                let fp = std::process::Command::new("ssh-keygen")
                    .args(["-l", "-f"])
                    .arg(&p)
                    .output()
                    .ok()
                    .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string());
                (Some(p.to_string_lossy().to_string()), fp)
            }
            None => (None, None),
        }
    } else {
        (None, None)
    };

    Ok(MigrationDetail {
        finding_id: entry.finding_id,
        action: entry.action,
        applied_at: entry.applied_at,
        summary: entry.detail,
        file_path,
        before,
        after,
        new_key_path,
        new_key_fingerprint,
    })
}

/// Roll back a previously applied migration by restoring the pre-change snapshot.
pub fn rollback(store: &Store, finding_id: &str) -> Result<String, String> {
    if finding_id == "net:wifi" {
        store.set_setting("force_tunnel_untrusted", "0");
        let msg = "Untrusted-network policy disabled.".to_string();
        store.log_remediation(finding_id, "rollback", &msg);
        return Ok(msg);
    }

    // SSH key findings share one config snapshot — restore it and clear every
    // related applied finding so the UI doesn't show a half-rolled-back state.
    if is_ssh_key_finding(finding_id) || finding_id == SSH_CONFIG_SNAPSHOT {
        let snap = store
            .latest_snapshot(SSH_CONFIG_SNAPSHOT)
            .ok_or("no SSH config snapshot recorded for this migration")?;
        match snap.content {
            Some(bytes) => std::fs::write(&snap.file_path, bytes).map_err(|e| e.to_string())?,
            None => {
                if std::path::Path::new(&snap.file_path).exists() {
                    std::fs::remove_file(&snap.file_path).map_err(|e| e.to_string())?;
                }
            }
        }
        let msg = format!(
            "Restored {} to its pre-migration state. The generated keypair at \
             ~/.ssh/cryptiq_ed25519 was kept (delete it manually if it was never uploaded anywhere).",
            snap.file_path
        );
        let mut ids: Vec<String> = store
            .applied_findings()
            .into_iter()
            .filter(|id| id == SSH_CONFIG_SNAPSHOT || is_ssh_key_finding(id))
            .collect();
        if !ids.iter().any(|id| id == finding_id) {
            ids.push(finding_id.to_string());
        }
        if !ids.iter().any(|id| id == SSH_CONFIG_SNAPSHOT) {
            ids.push(SSH_CONFIG_SNAPSHOT.to_string());
        }
        for id in ids {
            store.log_remediation(&id, "rollback", &msg);
        }
        return Ok(msg);
    }

    let snap = store
        .latest_snapshot(finding_id)
        .ok_or("no snapshot recorded for this migration")?;

    match snap.content {
        Some(bytes) => std::fs::write(&snap.file_path, bytes).map_err(|e| e.to_string())?,
        None => {
            // File didn't exist before the migration — remove what we created.
            if std::path::Path::new(&snap.file_path).exists() {
                std::fs::remove_file(&snap.file_path).map_err(|e| e.to_string())?;
            }
        }
    }

    let msg = format!(
        "Restored {} to its pre-migration state. The generated keypair at \
         ~/.ssh/cryptiq_ed25519 was kept (delete it manually if it was never uploaded anywhere).",
        snap.file_path
    );
    store.log_remediation(finding_id, "rollback", &msg);
    Ok(msg)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn managed_block_prefers_new_key_and_strong_host_algorithms() {
        let block = managed_block();
        assert!(block.contains("IdentityFile ~/.ssh/cryptiq_ed25519"));
        assert!(block.contains("HostKeyAlgorithms ssh-ed25519,"));
        // Legacy SHA-1 ssh-rsa must not be offered.
        assert!(!block.contains("HostKeyAlgorithms ssh-ed25519,ssh-rsa"));
    }

    #[test]
    fn upsert_inserts_into_empty_and_existing_configs() {
        let (fresh, changed) = upsert_managed_block("");
        assert!(changed);
        assert!(fresh.starts_with(BLOCK_START));

        let (appended, changed) = upsert_managed_block("Host github.com\n  User git\n");
        assert!(changed);
        assert!(appended.starts_with("Host github.com"));
        assert!(appended.contains(BLOCK_START));
    }

    #[test]
    fn upsert_is_idempotent_and_upgrades_stale_blocks() {
        let (v1, _) = upsert_managed_block("Host example\n  Port 22\n");
        let (v2, changed) = upsert_managed_block(&v1);
        assert!(!changed, "current block must not be rewritten");
        assert_eq!(v1, v2);

        // Simulate a config written by an older app version: same markers,
        // outdated body. It must be upgraded in place, preserving the rest.
        let stale = format!(
            "Host example\n  Port 22\n\n{BLOCK_START}\n# old body\nHost *\n  IdentityFile ~/.ssh/cryptiq_ed25519\n{BLOCK_END}\n# trailing user config\n"
        );
        let (upgraded, changed) = upsert_managed_block(&stale);
        assert!(changed);
        assert!(upgraded.contains("Host example"));
        assert!(upgraded.contains("# trailing user config"));
        assert!(!upgraded.contains("# old body"));
        assert!(upgraded.contains("HostKeyAlgorithms"));
        // Exactly one managed block after upgrade.
        assert_eq!(upgraded.matches(BLOCK_START).count(), 1);
    }
}
